### ISSUE TITLE
Want to upgrade to 4.2 kernel, steps to help bring my changes back to this repo

### ISSUE THREAD

**Issue by ianks** [matthewwardrop/linux-surfacepro3#9]
I am thinking about upgrading to the 4.2 kernel, and possibly bringing the changes upstream to this repo. What are some steps you follow when upgrading kernel versions?

**Comment by matthewwardrop** [comment]
Hi ianks,

I've updated the kernel to 4.2.2 today, and am compiling it on my surface pro 3. Normally I have access to another machine to do the compiling for me, so my surface pro 3 is getting quite hot ;).

My usual workflow is to merge the latest changes to config and config.x86_64 from the upstream official packages; update the PKGBUILD similarly; and then rewrite/update any patches that need adusting due to updates in the underlying source code.

A PKGBUILD for linux-surfacepro3 4.2.2 will be posted to AUR as soon as I've verified that the code compiles and works on my surface.
